version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wlm
      MYSQL_DATABASE: wlm
      MYSQL_USER: wlm
      MYSQL_PASSWORD: wlm
    ports:
    - "3306:3306"