env: ${ENV}

application:
  env: ${ENV}
  name: '@pom.name@'
  description: '@pom.description@'
  version: '@pom.version@'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wlm?useSSL=false&useUnicode=true&connectionCollation=utf8_general_ci&characterEncoding=UTF-8
    username: wlm
    password: wlm
    hikari:
      minimumIdle: ${HIKARI_MINIMUM_IDLE:10}
      maximumPoolSize: ${HIKARI_MAXIMUM_POLL_SIZE:10}

  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        connection:
          charSet: UTF-8
          characterEncoding: utf8_general_ci
          useUnicode: true
        dialect: org.hibernate.dialect.MySQL5Dialect

server.port: ${PORT:8080}

oauth:
  clientId: ${OAUTH_CLIENT_ID:admin}
  clientSecret: ${OAUTH_CLIENT_SECRET:secret}
  username: ${OAUTH_USERNAME:admin}
  password: ${OAUTH_PASSWORD:secret}
  expiresIn: ${OAUTH_EXPIRES_IN:86400}
  scopes: "web"
  grantTypes: "password"

swagger:
  enabled: true
  title: "WLM - Wish List Manager"
  description: "Project to manager wish list"
  useDefaultResponseMessages: false
  enableUrlTemplating: false
  deepLinking: true
  defaultModelsExpandDepth: 1
  defaultModelExpandDepth: 1
  displayOperationId: false
  displayRequestDuration: false
  filter: false
  maxDisplayedTags: 0
  showExtensions: false
  license: "GNU General Public License v3.0"
  licenseUrl: "https://github.com/danielrgn/wish-list-manager/blob/master/LICENSE"
  author: "Daniel Rigoni"
  githubUrl: "https://github.com/danielrgn"

api:
  challenge:
    product:
      url: "http://challenge-api.luizalabs.com/api/product/"
  retry:
    maxAttempts: ${RETRY_MAX_ATTEMPTS:3}
    waitDurationMilliseconds: ${RETRY_WAIT_DURATION_MILLISECONDS:5000}