env: ${ENV}

application:
  env: ${ENV}
  name: '@pom.name@'
  description: '@pom.description@'
  version: '@pom.version@'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wlm?useSSL=false
    username: wlm
    password: wlm
    connectionInitSql: "SET NAMES 'utf8mb4'"
    hikari:
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
      minimumIdle: ${HIKARI_MINIMUM_IDLE:10}
      maximumPoolSize: ${HIKARI_MAXIMUM_POLL_SIZE:10}

  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server.port: ${PORT:8080}

swagger:
  enabled: true
  title: "WLM - Wish List Manager"
  description: "Project to manager wish list"
  useDefaultResponseMessages: false
  enableUrlTemplating: false
  deepLinking: true
  defaultModelsExpandDepth: 1
  defaultModelExpandDepth: 1
  displayOperationId: false
  displayRequestDuration: false
  filter: false
  maxDisplayedTags: 0
  showExtensions: false
  license: "GNU General Public License v3.0"
  licenseUrl: "https://github.com/danielrgn/wish-list-manager/blob/master/LICENSE"
  author: "Daniel Rigoni"
  githubUrl: "https://github.com/danielrgn"