version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: ./mvnw checkstyle:check -q
      - run: ./mvnw dependency:go-offline -q

  test:
    docker:
      - image: circleci/openjdk:11
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: wlm
          MYSQL_DATABASE: wlm
          MYSQL_USER: wlm
          MYSQL_PASSWORD: wlm
    steps:
      - checkout
      - run: ./mvnw test jacoco:report
      - codecov/upload:
          file: '*jacoco.xml'
          token: 87303df9-c091-463e-bde3-89ab7a6563fe

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
