version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run: ./mvnw checkstyle:check -q
      - run: ./mvnw dependency:go-offline -q

  test:
    docker:
      - image: circleci/openjdk:11
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: wlm
          MYSQL_DATABASE: wlm
          MYSQL_USER: wlm
          MYSQL_PASSWORD: wlm
    steps:
      - checkout
      - run: ./mvnw test jacoco:report
      - run: cat target/site/jacoco/index.html

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
